package com.personal.erg.models;

public enum HazmatClass {

    HAZMAT_CLASS_1_EXPLOSIVES,
    HAZMAT_CLASS_2_GASES,
    HAZMAT_CLASS_3_FLAMMABLE_LIQUIDS,
    HAZMAT_CLASS_4_FLAMMABLE_SOLIDS,
    HAZMAT_CLASS_5_OXIDIZERS,
    HAZMAT_CLASS_6_POISON,
    HAZMAT_CLASS_7_RADIOACTIVE,
    HAZMAT_CLASS_8_CORROSIVE,
    HAZMAT_CLASS_9_MISCELLANEOUS;

}
